services:
  app-blue:
    image: ghcr.io/${ORG_NAME}/spring-api:latest
    ports:
      - "8080:8080"
    env_file:
      - /home/ubuntu/backend/docker/.env
    volumes:
      - /home/ubuntu/logs:/app/logs
    depends_on:
      - redis
    networks:
      - my-network
    container_name: app-blue

  app-green:
    image: ghcr.io/${ORG_NAME}/spring-api:latest
    ports:
      - "8081:8080"
    env_file:
      - .env
    volumes:
      - /home/ubuntu/logs:/app/logs
    depends_on:
      - redis
    networks:
      - my-network
    container_name: app-green

  redis:
    image: redis:7.4.1
    restart: always
    volumes:
      - /home/ubuntu/redis/redis.conf:/usr/local/etc/redis/redis.conf:ro
      - /home/ubuntu/redis/redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - my-network
    container_name: redis
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]

  nginx:
    image: nginx:1.27.4
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /home/ubuntu/backend/deploy/nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - app-blue
      - app-green
    networks:
      - my-network
    restart: always

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep sleep 12h & wait $${!}; done;'"
    networks:
      - my-network

volumes:
  redis_data:

networks:
  my-network:
    driver: bridge