services:
  app-blue:
    image: ghcr.io/${ORG_NAME}/spring-api:latest
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - /home/ubuntu/logs:/app/logs
    depends_on:
      - redis
    networks:
      - my-network
    container_name: app-blue

  app-green:
    image: ghcr.io/${ORG_NAME}/spring-api:latest
    ports:
      - "8081:8080"
    env_file:
      - .env
    volumes:
      - /home/ubuntu/logs:/app/logs
    depends_on:
      - redis
    networks:
      - my-network
    container_name: app-green

  redis:
    image: redis:7.4.1
    restart: always
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - my-network
    container_name: redis

  nginx:
    image: nginx:1.27.4
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - /home/ubuntu/deploy/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app-blue
      - app-green
    networks:
      - my-network
    restart: always

volumes:
  redis_data:

networks:
  my-network:
    driver: bridge