server:
  port: 8080

spring:
  application:
    name: "backend"
  config:
    activate:
      on-profile: "dev"

  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration
    baseline-version: 1
    enabled: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DEV_DB_URL}
    username: ${DEV_DB_USER}
    password: ${DEV_DB_PASSWORD}

  data:
    redis:
      host: ${DEV_REDIS_HOST}
      port: 6379
      password: ${DEV_REDIS_PASSWORD}

  jwt:
    secret: ${JWT_SECRET_KEY}
    access:
      expiration: 86400      # 24시간 (24 * 60 * 60 초)
    refresh:
      expiration: 604800     # 7일 (7 * 24 * 60 * 60 초)

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-handlers-package: com.yachaerang.backend.global.util

logging:
  level:
    org.apache.ibatis: INFO