server:
  port: 8080

spring:
  application:
    name: "backend"
  config:
    activate:
      on-profile: "local"

  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration
    baseline-version: 1
    enabled: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${LOCAL_DB_URL}
    username: ${LOCAL_DB_USER}
    password: ${LOCAL_DB_PASSWORD}

  data:
    redis:
      host: ${LOCAL_REDIS_HOST}
      port: 6379
      password: ${LOCAL_REDIS_PASSWORD}

  jwt:
    secret: ${JWT_SECRET_KEY}
    access:
      expiration: 1800
    refresh:
      expiration: 604800

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:/mappers/*/*.xml
  type-handlers-package: com.yachaerang.backend.global.util