server:
  port: 8080

spring:
  application:
    name: "backend"
  config:
    activate:
      on-profile: "local"

  flyway:
    baseline-on-migrate: true
    locations:
      - classpath:db/migration
      - classpath:db/seed/local
    baseline-version: 1
    enabled: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${LOCAL_DB_URL}
    username: ${LOCAL_DB_USER}
    password: ${LOCAL_DB_PASSWORD}

  data:
    redis:
      host: ${LOCAL_REDIS_HOST}
      port: 6379
      password: ${LOCAL_REDIS_PASSWORD}

  jwt:
    secret: ${JWT_SECRET_KEY}
    access:
      expiration: 86400      # 24시간 (24 * 60 * 60 초)
    refresh:
      expiration: 604800     # 7일 (7 * 24 * 60 * 60 초)

  ai:
    vertex:
      ai:
        enabled: false
    google:
      genai:
        enabled: false
    custom:
      google:
        genai:
          api-key: ${GMS_KEY}
          model: gemini-2.5-flash-lite
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-handlers-package: com.yachaerang.backend.global.util

logging:
  file:
    path: ./logs
  config: classpath:logback-spring.xml
  level:
    root: info

cloud:
  aws:
    region:
      static: ${AWS_REGION}
    s3:
      bucket: ${AWS_S3_BUCKET}
    stack:
      auto: false
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}

external:
  default-image: ${DEFAULT_IMAGE}