name: Deploy Workflows

permissions:
  contents: read
  packages: write

on:
  push:
    branches:
      - main
    workflow_dispatch:
      inputs:
        deploy-target:
          description: 'Select Deployment target'
          required: true
          type: choice
          options:
            - all
            - backend
            - batch
            - frontend

jobs:
  detect-changes:
    name: Detect changes
    runs-on: ubuntu-latest
    outputs:
      backend: ${{ steps.filter.outputs.backend }}
      batch: ${{ steps.filter.outputs.batch }}
      frontend: ${{ steps.filter.outputs.frontend }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Auto
      - name: Filter paths
        uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            backend:
              - 'backend/**'
            batch:
              - 'batch/**'
            frontend:
              - 'frontend/**'

      # Select
      - name: Select Deployment target
        if: github.event_name == 'workflow_dispatch'
        id: manual
        run: |
          TARGET="${{ github.event.inputs.deploy-target }}"
          
          if [ "$TARGET" = "all" ] || [ "$TARGET" = "backend" ]; then
            echo "backend=true" >> $GITHUB_OUTPUT
          else
            echo "backend=false" >> $GITHUB_OUTPUT
          fi
          
          if [ "$TARGET" = "all" ] || [ "$TARGET" = "batch" ]; then
            echo "batch=true" >> $GITHUB_OUTPUT
          else
            echo "batch=false" >> $GITHUB_OUTPUT
          fi
          
          if [ "$TARGET" = "all" ] || [ "$TARGET" = "frontend" ]; then
            echo "frontend=true" >> $GITHUB_OUTPUT
          else
            echo "frontend=false" >> $GITHUB_OUTPUT
          fi 

  # backend Deploy
  deploy-backend:
    needs: detect-changes
    if: needs.detect-changes.outputs.backend == 'true'
    uses: ./.github/workflows/backend-deploy.yaml
    secrets: inherit

  # batch Deploy
  deploy-batch:
    needs: detect-changes
    if: needs.detect-changes.outputs.batch == 'true'
    uses: ./.github/workflows/batch-deploy.yaml
    secrets: inherit

  # frontend Deploy
  deploy-frontend:
    needs: detect-changes
    if: needs.detect-changes.outputs.frontend == 'true'
    uses: ./.github/workflows/frontend-deploy.yaml
    secrets: inherit