name: deploy.yaml
on:

jobs:
  # Detect Change
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      backend: ${{ steps.filter.outputs.backend }}
      batch: ${{ steps.filter.outputs.batch }}
      frontend: ${{ steps.filter.outputs.frontend }}
    steps:
      - uses: actions/checkout@v3

      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            backend:
              - 'backend/**'
            batch:
              - 'batch/**'
            frontend:
              - 'frontend/**'

  # backend Deploy
  deploy-backend:
    needs: detect-changes
    if: needs.detect-changes.outputs.backend == 'true'
    uses: ./.github/workflows/backend-deploy.yaml
    secrets: inherit

  # batch Deploy
  deploy-batch:
    needs: detect-changes
    if: needs.detect-changes.outputs.batch == 'true'
    uses: ./.github/workflows/batch-deploy.yaml
    secrets: inherit

  # frontend Deploy
  deploy-frontend:
    needs: detect-changes
    if: needs.detect-changes.outputs.frontend == 'true'
    uses: ./.github/workflows/frontend-deploy.yaml
    secrets: inherit