name: Frontend Deploy

on:
  workflow_run:
    workflows: ['backend-deploy.yaml']
    types:
      - completed
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker Login to GHCR
        run: echo ${{ secrets.YY_GITHUB_PAT }} | docker login ghcr.io -u ${{ secrets.YY_GITHUB_USERNAME }} --password-stdin

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Docker Image
        run: |
          cd frontend
          docker build -t ghcr.io/${{ secrets.ORG_NAME }}/frontend:latest .
          docker push ghcr.io/${{ secrets.ORG_NAME }}/frontend:latest
        build-args: |
          VITE_API_URL=${{ secrets.VITE_API_URL }}

  transfer:
    name: Transfer
    runs-on: ubuntu-22.04
    needs: build-and-push
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Transfer docker-compose.dev.yaml file to ec2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: ./frontend/docker-compose.dev.yaml
          target: /home/ubuntu/

  deploy:
    needs: transfer
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            mkdir -p /home/ubuntu/frontend
            cd /home/ubuntu/frontend

            # GHCR 로그인
            echo "${{ secrets.YY_GITHUB_PAT }}" | docker login ghcr.io -u ${{ secrets.YY_GITHUB_USERNAME }} --password-stdin

            # 환경변수 설정
            export ORG_NAME=${{ secrets.ORG_NAME }}

            # 이미지 pull & 재시작
            docker compose pull
            docker compose up -d --force-recreate

            # Nginx 설정 리로드
            docker exec nginx nginx -s reload

            # 사용하지 않는 이미지 정리
            docker image prune -f

            echo "Frontend deployment completed!"
