name: Frontend Deploy

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker Login to GHCR
        run: echo ${{ secrets.YY_GITHUB_PAT }} | docker login ghcr.io -u ${{ secrets.YY_GITHUB_USERNAME }} --password-stdin

      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Docker Image
        run: |
          cd frontend
          docker build \
            --build-arg VITE_API_BASE_URL=${{ secrets.VITE_API_URL }} \
            -t ghcr.io/${{ secrets.ORG_NAME }}/frontend:latest .
          docker push ghcr.io/${{ secrets.ORG_NAME }}/frontend:latest

  transfer:
    name: Transfer
    runs-on: ubuntu-22.04
    needs: build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

  deploy:
    needs: transfer
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/deploy

            # GHCR 로그인
            echo "${{ secrets.YY_GITHUB_PAT }}" | docker login ghcr.io -u ${{ secrets.YY_GITHUB_USERNAME }} --password-stdin

            # 환경변수 설정
            export ORG_NAME=${{ secrets.ORG_NAME }}

            # 이미지 pull & 재시작
            docker compose -f docker-compose.dev.yaml pull frontend
            docker compose -f docker-compose.dev.yaml up -d --force-recreate frontend

            # 사용하지 않는 이미지 정리
            docker image prune -f

            echo "Frontend deployment completed!"
